/*
 RequireJS domReady 2.0.1 Copyright (c) 2010-2012, The Dojo Foundation All Rights Reserved.
 Available via the MIT or new BSD license.
 see: http://github.com/requirejs/domReady for details
 MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors  MIT License (c) copyright 2010-2014 original author or authors */
define("third_party/domready/domReady",[],function(){function d(){if(!g){g=!0;e&&clearInterval(e);var a=m;if(g&&a.length){m=[];var c;for(c=0;c<a.length;c+=1)a[c](k)}}}function b(a){g?a(k):m.push(a);return b}var c,a,e,f="undefined"!==typeof window&&window.document,g=!f,k=f?document:null,m=[];if(f){if(document.addEventListener)document.addEventListener("DOMContentLoaded",d,!1),window.addEventListener("load",d,!1);else if(window.attachEvent){window.attachEvent("onload",d);a=document.createElement("div");
try{c=null===window.frameElement}catch(l){}a.doScroll&&c&&window.external&&(e=setInterval(function(){try{a.doScroll(),d()}catch(c){}},30))}"complete"===document.readyState&&d()}b.version="2.0.1";b.load=function(a,c,d,e){e.isBuild?d(null):b(d)};return b});
define("qowtRoot/utils/typeUtils",[],function(){function d(a,b,d){if(d.types.every(function(a){var b=c[a];if(!b)throw Error("Bad config to checkArgTypes: unknown type: "+a);return!b(d.value)})){var g=1===d.types.length?d.types[0]:"["+d.types.join(",")+"]";throw Error("Argument "+b+" passed to function "+a+" was supposed to be of type "+g+" but had value "+d.value);}}var b={checkArgTypes:function(a,c){for(var b in c){var g={value:c[b][0],types:c[b].slice(1)};d(a,b,g)}},isObject:function(a){return"object"===
typeof a&&null!==a},isPromise:function(a){return a instanceof Promise},isPromiseLike:function(a){return!(!a||!b.isFunction(a.then))},isList:function(a){return"[object Array]"===Object.prototype.toString.call(a)},isNumber:function(a){return"number"===typeof a&&!isNaN(a)},isInteger:function(a){return"number"===typeof a&&parseInt(a,10)===a},isFunction:function(a){return"function"===typeof a},isString:function(a){return"[object String]"===Object.prototype.toString.call(a)},isRegex:function(a){return"[object RegExp]"===
Object.prototype.toString.call(a)},isNode:function(a){return a instanceof Node},isNull:function(a){return null===a},isUndefined:function(a){return void 0===a},isBoolean:function(a){return"boolean"===typeof a},getType:function(a){var b;Object.keys(c).forEach(function(d){c[d](a)&&(b=d)});return b},isArgumentsObjectOrList:function(a){return a instanceof Object&&a.hasOwnProperty("length")},extend:function(a,c){for(var b in c)c.hasOwnProperty(b)&&(a[b]=c[b])},createNewType:function(a){var b=function(){},
d={isOfType:function(a){return void 0!==a&&null!==a&&a.constructor===b},markAsType:function(a){Object.defineProperty(a,"constructor",{value:b,configurable:!1,writable:!1,enumerable:!1});return a}};if(a){if(c[a])throw Error("Already registered type "+a);c[a]=d.isOfType}return d}},c={string:b.isString,object:b.isObject,promise:b.isPromise,promiseLike:b.isPromiseLike,node:b.isNode,regex:b.isRegex,"function":b.isFunction,number:b.isNumber,list:b.isList,boolean:b.isBoolean,"null":b.isNull,undefined:b.isUndefined};
return b});(function(){var d={},b=window.sessionStorage.getItem("featureOverrides");b&&(d=JSON.parse(b));d.isRelease=!0;d.edit=!1;window.sessionStorage.setItem("featureOverrides",JSON.stringify(d));window.localStorage.removeItem("testsToInclude");window.localStorage.removeItem("builtInTests")})();define("configs/releaseFeatures",function(){});
(function(){var d={},b=window.sessionStorage.getItem("featureOverrides");b&&(d=JSON.parse(b));d.save=!!(window.chrome&&window.chrome.fileSystem&&window.chrome.fileSystem.chooseEntry);window.sessionStorage.setItem("featureOverrides",JSON.stringify(d))})();define("configs/chromeFeatures",function(){});define("qowtRoot/features/pack",[],function(){return{edit:!0,save:!1,pointEdit:!1,hats:!0}});
define("qowtRoot/features/utils",["qowtRoot/features/pack"],function(d){var b={isEnabled:function(a){a=d[a];return void 0===a?!1:a},enable:function(a){d[a]=!0},disable:function(a){d[a]=!1},setOverrides:function(a){for(var b in a)a.hasOwnProperty(b)&&(d[b]=a[b])},isDebug:function(){return void 0!==c?c:!b.isEnabled("isRelease")},setDebugOverride:function(a){c=a},clearDebugOverride:function(){c=void 0}},c;return b});
(function(d){d("qowtRoot/third_party/when/lib/timer",["require"],function(b){return{set:setTimeout,clear:clearTimeout}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/timed",[],function(){return function(b,c,a){a.prototype.delay=function(a){var c=this;return new this.constructor(function(d,k,m){c.then(function(c){b(function(){d(c)},a)},k,m)})};a.prototype.timeout=function(a,d){var g=this,k=1<arguments.length;return new this.constructor(function(m,l,t){var n=b(function(){l(k?d:Error("timed out after "+a+"ms"))},a);g.then(function(a){c(n);m(a)},function(a){c(n);l(a)},t)})};return a}})})("function"===typeof define&&define.amd?
define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/array",[],function(){return function(b){var c=Array.prototype.map,a=Array.prototype.reduce,d=Array.prototype.reduceRight,f=Array.prototype.forEach,g=b.resolve,k=b.all;b.any=function(a){return new b(function(b,c){function d(a){k.push(a);0===--e&&c(k)}var e=0,k=[];f.call(a,function(a){++e;g(a).then(b,d)});0===e&&b()})};b.some=function(a,c){return new b(function(b,d,e){function k(a){0<h&&(--h,p.push(a),0===h&&b(p))}function u(a){0<q&&(--q,v.push(a),0===q&&
d(v))}var h=0,q,p=[],v=[];f.call(a,function(a){++h;g(a).then(k,u,e)});c=Math.max(c,0);q=h-c+1;h=Math.min(c,h);0===h&&b(p)})};b.settle=function(a){return k(c.call(a,function(a){function b(){return a.inspect()}a=g(a);return a.then(b,b)}))};b.map=function(a,b,d){return k(c.call(a,function(a){return g(a).then(b,d)}))};b.reduce=function(b,c){function d(a,b,e){return g(a).then(function(a){return g(b).then(function(b){return c(a,b,e)})})}return 2<arguments.length?a.call(b,d,arguments[2]):a.call(b,d)};b.reduceRight=
function(a,b){function c(a,d,e){return g(a).then(function(a){return g(d).then(function(c){return b(a,c,e)})})}return 2<arguments.length?d.call(a,c,arguments[2]):d.call(a,c)};b.prototype.spread=function(a){return this.then(k).then(function(b){return a.apply(void 0,b)})};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/fatal",["require","./timer"],function(b){var c=b("./timer").set;return function(a){c(function(){throw a;},0)}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/flow",["require","./fatal"],function(b){function c(){throw new TypeError("catch predicate must be a function");}function a(a,b){return function(){a.call(this);return b}}function d(){}var f=b("./fatal");return function(b){function k(a,b){return function(c){return(b===Error||null!=b&&b.prototype instanceof Error?c instanceof b:b(c))?a.call(this,c):l(c)}}var m=b.resolve,l=b.reject,t=b.prototype["catch"];b.prototype.done=function(a,b){var c=this._handler;
c.when(this._maybeFatal,d,this,c.receiver,a,b)};b.prototype._maybeFatal=function(a){if(Object(a)===a)m(a)["catch"](this._fatal)};b.prototype._fatal=f;b.prototype["catch"]=b.prototype.otherwise=function(a){return 1===arguments.length?t.call(this,a):"function"!==typeof a?this.ensure(c):t.call(this,k(arguments[1],a))};b.prototype["finally"]=b.prototype.ensure=function(b){if("function"!==typeof b)return this;b=a(b,this);return this.then(b,b)};b.prototype["else"]=b.prototype.orElse=function(a){return this.then(void 0,
function(){return a})};b.prototype.yield=function(a){return this.then(function(){return a})};b.prototype.tap=function(a){return this.then(a).yield(this)};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});(function(d){d("qowtRoot/third_party/when/lib/inspect",[],function(){return function(b){b.prototype.inspect=function(){return this._handler.inspect()};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/iterate",[],function(){return function(b){function c(a,b,k,m){function l(l){return d(k(l)).then(function(){return c(a,b,k,a(l))})}return d(m).then(function(a){return d(b(a)).then(function(b){return b?a:l(a)})})}function a(b,c,k,m){function l(l,m){return d(k(l)).then(function(){return a(b,c,k,m)})}return d(m).then(function(a){return d(c(a)).then(function(c){return c?a:d(b(a)).spread(l)})})}var d=b.resolve;b.iterate=c;b.unfold=a;return b}})})("function"===
typeof define&&define.amd?define:function(d){module.exports=d()});(function(d){d("qowtRoot/third_party/when/lib/progress",[],function(){return function(b){b.prototype.progress=function(b){return this.then(void 0,void 0,b)};return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/with",[],function(){return function(b){b.prototype["with"]=b.prototype.withThis=b.prototype._bindContext;return b}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/makePromise",[],function(){return function(b){function c(b){var c=this;this._handler=new n;a(b,function(a){c._handler.resolve(a)},function(a){c._handler.reject(a)},function(a){c._handler.notify(a)})}function a(a,b,c,d){try{a(b,c,d)}catch(e){c(e)}}function d(a){return new f(new x(new q(a)))}function f(a){this._handler=a}function g(a,b){if(a instanceof c){var d=a._handler.join();return b===d?new q(new TypeError("Promise cycle")):d}return C(a)?m(a):new h(a)}
function k(a){return a instanceof c?a._handler.join():m(a)}function m(a){try{var b=a.then;return"function"===typeof b?new u(b,a):new h(a)}catch(c){return new q(c)}}function l(){}function t(a){this.handler=a;if(this._isMonitored()){var b=this._env.promiseMonitor.captureStack();this.trace=a._addTrace(b)}}function n(a){this.consumers=[];this.receiver=a;this.handler=void 0;this.resolved=!1;this._isMonitored()&&(this.trace=this._env.promiseMonitor.captureStack())}function x(a){t.call(this,a)}function z(a,
b){t.call(this,a);this.receiver=b}function u(a,b){n.call(this);this.assimilated=!1;this.untrustedThen=a;this.thenable=b}function h(a){this.value=a}function q(a){this.value=a;this.observed=!1;this._isMonitored()&&(this.key=this._env.promiseMonitor.startTrace(a))}function p(){return{state:"pending"}}function v(a,b,c,d,e,f,r,k){this.a=a;this.b=b;this.c=c;this.d=d;this.e=e;this.f=f;this.g=r;this.handler=k}function r(a,b){this.q=a;this.value=b}function C(a){return("object"===typeof a||"function"===typeof a)&&
null!==a}function D(a,b,c){try{return a.call(c,b)}catch(f){return d(f)}}function w(){}var B,A=b.scheduler,y=Object.create||function(a){function b(){}b.prototype=a;return new b};c.resolve=function(a){return a instanceof c?a:new f(new x(g(a)))};c.reject=d;c.never=function(){return B};c._defer=function(){return new f(new n)};c.prototype.then=function(a,b,c){var d=this._handler,e=new n(d.receiver);d.when(e.resolve,e.notify,e,d.receiver,a,b,c);return new f(e)};c.prototype["catch"]=c.prototype.otherwise=
function(a){return this.then(void 0,a)};c.prototype._bindContext=function(a){return new f(new z(this._handler,a))};c.all=function(a){function b(a,c,d,f){d.when(w,w,void 0,a,function(a){c[f]=a;0===--e&&this.resolve(c)},a.reject,a.notify)}var c=new n,d=a.length>>>0,e=d,r=[],g,h;for(g=0;g<d;++g)g in a?(h=a[g],C(h)?b(c,r,k(h),g):(r[g]=h,--e)):--e;0===e&&c.resolve(r);return new f(c)};c.race=function(a){if(Object(a)===a&&0===a.length)return B;for(var b=new n,c=0;c<a.length;++c)g(a[c]).when(w,w,void 0,b,
b.resolve,b.reject);return new f(b)};f.prototype=y(c.prototype);l.prototype.inspect=p;l.prototype.when=w;l.prototype.resolve=w;l.prototype.reject=w;l.prototype.notify=w;l.prototype.join=function(){return this};l.prototype._env=b.monitor||c;l.prototype._addTrace=w;l.prototype._isMonitored=function(){return"undefined"!==typeof this._env.promiseMonitor};t.prototype=y(l.prototype);t.prototype.join=function(){return this.handler.join()};t.prototype.inspect=function(){return this.handler.inspect()};t.prototype._addTrace=
function(a){return this.handler._addTrace(a)};n.prototype=y(l.prototype);n.prototype.inspect=function(){return this.resolved?this.handler.join().inspect():p()};n.prototype.resolve=function(a){this._join(g(a,this))};n.prototype.reject=function(a){this._join(new q(a))};n.prototype.join=function(){return this.resolved?this.handler.join():this};n.prototype.run=function(){var a=this.consumers,b=this.handler=this.handler.join();this.consumers=void 0;for(var c=0;c<a.length;c+=7)b.when(a[c],a[c+1],a[c+2],
a[c+3],a[c+4],a[c+5],a[c+6])};n.prototype._join=function(a){this.resolved||(this.resolved=!0,this.handler=a,A.enqueue(this),this._isMonitored()&&(this.trace=a._addTrace(this.trace)))};n.prototype.when=function(a,b,c,d,e,f,r){this.resolved?A.enqueue(new v(a,b,c,d,e,f,r,this.handler.join())):this.consumers.push(a,b,c,d,e,f,r)};n.prototype.notify=function(a){this.resolved||A.enqueue(new r(this.consumers,a))};n.prototype._addTrace=function(a){return this.resolved?this.handler._addTrace(a):a};x.prototype=
y(t.prototype);x.prototype.when=function(a,b,c,d,e,f,r){A.enqueue(new v(a,b,c,d,e,f,r,this.join()))};z.prototype=y(t.prototype);z.prototype.when=function(a,b,c,d,e,f,r){void 0!==this.receiver&&(d=this.receiver);this.join().when(a,b,c,d,e,f,r)};u.prototype=y(n.prototype);u.prototype.when=function(a,b,c,d,e,f,r){this.assimilated||(this.assimilated=!0,this._assimilate());n.prototype.when.call(this,a,b,c,d,e,f,r)};u.prototype._assimilate=function(){var a=this;this._try(this.untrustedThen,this.thenable,
function(b){a.resolve(b)},function(b){a.reject(b)},function(b){a.notify(b)})};u.prototype._try=function(a,b,c,d,e){try{a.call(b,c,d,e)}catch(f){d(f)}};h.prototype=y(l.prototype);h.prototype.inspect=function(){return{state:"fulfilled",value:this.value}};h.prototype.when=function(a,b,c,d,e){b="function"===typeof e?D(e,this.value,d):this.value;a.call(c,b)};q.prototype=y(l.prototype);q.prototype.inspect=function(){return{state:"rejected",reason:this.value}};q.prototype.when=function(a,b,c,f,r,g){this._isMonitored()&&
!this.observed&&this._env.promiseMonitor.removeTrace(this.key);this.observed=!0;b="function"===typeof g?D(g,this.value,f):d(this.value);a.call(c,b)};q.prototype._addTrace=function(a){this.observed||this._env.promiseMonitor.updateTrace(this.key,a)};B=new f(new l);v.prototype.run=function(){this.handler.when(this.a,this.b,this.c,this.d,this.e,this.f,this.g)};r.prototype.run=function(){for(var a=this.q,b=1;b<a.length;b+=7)this._notify(a[b],a[b+1],a[b+2],a[b+5])};r.prototype._notify=function(a,b,c,d){var e;
if("function"===typeof d)try{e=d.call(c,this.value)}catch(f){e=f}else e=this.value;a.call(b,e)};return c}})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/Queue",[],function(){function b(b){this.head=this.tail=this.length=0;this.buffer=Array(1<<b)}b.prototype.push=function(b){this.length===this.buffer.length&&this._ensureCapacity(2*this.length);this.buffer[this.tail]=b;this.tail=this.tail+1&this.buffer.length-1;++this.length;return this.length};b.prototype.shift=function(){var b=this.buffer[this.head];this.buffer[this.head]=void 0;this.head=this.head+1&this.buffer.length-1;--this.length;return b};b.prototype._ensureCapacity=
function(b){var a=this.head,d=this.buffer,f=Array(b),g=0,k;if(0===a)for(k=this.length;g<k;++g)f[g]=d[g];else{b=d.length;for(k=this.tail;a<b;++g,++a)f[g]=d[a];for(a=0;a<k;++g,++a)f[g]=d[a]}this.buffer=f;this.head=0;this.tail=this.length};return b})})("function"===typeof define&&define.amd?define:function(d){module.exports=d()});
(function(d){d("qowtRoot/third_party/when/lib/scheduler",["require","./Queue"],function(b){function c(b){this._enqueue=b;this._handlerQueue=new a(15);var c=this;this.drainQueue=function(){c._drainQueue()}}var a=b("./Queue");c.prototype.enqueue=function(a){1===this._handlerQueue.push(a)&&this._enqueue(this.drainQueue)};c.prototype._drainQueue=function(){for(var a=this._handlerQueue;0<a.length;)a.shift().run()};return c})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/lib/async",["require"],function(b){var c;return"undefined"!==typeof process&&null!==process&&"function"===typeof process.nextTick?function(a){process.nextTick(a)}:(c="function"===typeof MutationObserver&&MutationObserver||"function"===typeof WebKitMutationObserver&&WebKitMutationObserver)?function(a,b){var c,d=a.createElement("div");(new b(function(){var a=c;c=void 0;a()})).observe(d,{attributes:!0});return function(a){c=a;d.setAttribute("class","x")}}(document,
c):function(a){var b=setTimeout;return function(a){b(a,0)}}(b)})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});(function(d){d("qowtRoot/third_party/when/lib/Promise",["require","./makePromise","./scheduler","./async"],function(b){var c=b("./makePromise"),a=b("./scheduler");b=b("./async");return c({scheduler:new a(b),monitor:"undefined"!==typeof console?console:void 0})})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
(function(d){d("qowtRoot/third_party/when/when","require ./lib/timer ./lib/timed ./lib/array ./lib/flow ./lib/inspect ./lib/iterate ./lib/progress ./lib/with ./lib/Promise".split(" "),function(b){function c(a,b,c,d){var e=q(a);return 2>arguments.length?e:e.then(b,c,d)}function a(a){return function(){return f(a,this,p.call(arguments))}}function d(a){return f(a,this,p.call(arguments,1))}function f(a,b,c){return h.all(c).then(function(c){return a.apply(b,c)})}function g(){function a(b){d._handler.resolve(b)}
function b(a){d._handler.reject(a)}function c(a){d._handler.notify(a)}var d=h._defer();this.promise=d;this.resolve=a;this.reject=b;this.notify=c;this.resolver={resolve:a,reject:b,notify:c}}var k=b("./lib/timer"),m=b("./lib/timed"),l=b("./lib/array"),t=b("./lib/flow"),n=b("./lib/inspect"),x=b("./lib/iterate"),z=b("./lib/progress"),u=b("./lib/with"),h=b("./lib/Promise"),h=[l,t,x,z,n,u].reduceRight(function(a,b){return b(a)},m(k.set,k.clear,h)),q=h.resolve,p=Array.prototype.slice;c.promise=function(a){return new h(a)};
c.resolve=h.resolve;c.reject=h.reject;c.lift=a;c["try"]=d;c.attempt=d;c.iterate=h.iterate;c.unfold=h.unfold;c.join=function(){return h.all(arguments)};c.all=function(a){return c(a,h.all)};c.settle=function(a){return c(a,h.settle)};c.any=a(h.any);c.some=a(h.some);c.map=function(a,b){return c(a,function(a){return h.map(a,b)})};c.reduce=function(a,b){var d=p.call(arguments,1);return c(a,function(a){d.unshift(a);return h.reduce.apply(h,d)})};c.reduceRight=function(a,b){var d=p.call(arguments,1);return c(a,
function(a){d.unshift(a);return h.reduceRight.apply(h,d)})};c.isPromiseLike=function(a){return a&&"function"===typeof a.then};c.Promise=h;c.defer=function(){return new g};return c})})("function"===typeof define&&define.amd?define:function(d){module.exports=d(require)});
define("qowtRoot/utils/promiseUtils",["qowtRoot/utils/typeUtils","qowtRoot/third_party/when/when"],function(d,b){var c={cast:function(a){return a instanceof Promise?a:Promise.resolve(a)},delay:function(a,b){a=a||0;return new Promise(function(c){setTimeout(c.bind(void 0,b),a)})},delayThenReject:function(a,b){a=a||0;return new Promise(function(c,d){setTimeout(d.bind(c,b),a)})},throwAndEscapeChain:function(a){a instanceof Error||(console.error("throwAndEscapeChain wrapping value in new Error: ",a),a=
Error(a));b.reject(a).done();throw a;},pipeline:function(a){function b(){for(var g=Array.prototype.slice.call(arguments,0);0<a.length;){var m=a.shift();if(d.isPromiseLike(m))return c.cast(m).then(function(c){a.unshift(c);return b.apply(f,g)});d.checkArgTypes("PromiseUtils.pipeline",{task:[m,"function"]});m=m.apply(f,g);if(d.isPromiseLike(m))return c.cast(m).then(function(a){return b(a)});g=[m]}return g[0]}var f=this,g=Array.prototype.slice.call(arguments,0);if(g.some(d.isPromiseLike))return Promise.all(g).then(function(a){return c.pipeline.apply(f,
a)});d.checkArgTypes("PromiseUtils.pipeline",{tasks:[a,"list"]});a=a.slice(0);return b.apply(f,g.slice(1))},finally:function(a,b){function d(){return c.cast(b()).then(function(){return a})}return c.cast(a).then(d,d)},waitForNextMacroTurn:function(a){return new Promise(function(b){window.setTimeout(b.bind(null,a),0)})}};return c});
define("utils/analytics/googleAnalytics",["qowtRoot/features/utils","qowtRoot/utils/promiseUtils"],function(d,b){function c(b,c){var e;void 0!==h?e=h?Promise.resolve():Promise.reject(Error("ga permission cached (not permitted)")):(window.analytics&&chrome&&chrome.metricsPrivate&&chrome.metricsPrivate.getIsCrashReportingEnabled&&(!d.isDebug()||void 0!==window.__gaMock)?e=Promise.resolve():(console.warn("GA not supported on this platform"),e=Promise.reject(Error("GA not supported on this platform"))),
e=e.then(a).catch(g));return e.then(k).then(b.bind(null,c)).catch(function(){})}function a(){var a=Error("Crash reporting setting timed out");return Promise.race([e(),b.delayThenReject(1E3,a)]).then(f)}function e(){return new Promise(function(a){chrome.metricsPrivate.getIsCrashReportingEnabled(a)})}function f(a){return new Promise(function(b,c){q=window.analytics.getService(z);q.getConfig().addCallback(function(d){d.setTrackingPermitted(a);(h=a)?b():(console.warn("Crash reporting not allowed"),c())})})}
function g(){h=!1;return Promise.reject()}function k(){void 0===p&&m("QO");return Promise.resolve()}function m(a){p&&p.sendAppView(a);p=q.getTracker(x[a]);v&&p.set(window.analytics.Parameters.SESSION_GROUP,v);p.forceSessionStart();return Promise.resolve()}function l(a){u!==a&&(u=a,p.sendAppView(a));return Promise.resolve()}function t(a){p.sendException(a.msg,a.fatal);return Promise.resolve()}function n(a){p.sendEvent(a.category,a.action,a.label,a.value);return Promise.resolve()}var x={word:"UA-44583639-1",
sheet:"UA-44583639-2",point:"UA-44583639-3",QO:"UA-44583639-4"},z="Quickoffice",u,h,q,p,v;return{setSessionGroup:function(a){v=a},setTracker:function(a){return c(m,a)},sendState:function(a){return c(l,a)},sendException:function(a){return c(t,a)},sendEvent:function(a){return c(n,a)},reset:function(){p=q=h=u=void 0}}});
define("qowtRoot/utils/i18n",["qowtRoot/utils/typeUtils","utils/analytics/googleAnalytics"],function(d,b){var c={getMessage:function(a,b){var f="????";if(!chrome||!chrome.i18n)return a;d.isString(a)?(f=chrome.i18n.getMessage(a,b),f||(f=a,c.logError_("Missing translation",a))):c.logError_("Invalid string translation Id",a);return f},logError_:function(a,c){console.error(a+" "+c);b.sendException({msg:a,fatal:!1})}};return c});
require(["third_party/domready/domReady!"],function(){require(["qowtRoot/utils/i18n"],function(d){var b=d.getMessage("extension_popup_new_document_header");document.getElementById("newHeading").textContent=b;var b=d.getMessage("extension_popup_new_spreadsheet_document"),b=createOption(b,"sheet"),c=d.getMessage("extension_popup_new_presentation_document"),c=createOption(c,"point"),a=d.getMessage("extension_popup_new_word_document"),a=createOption(a,"word"),e=document.getElementById("options");e.appendChild(b);
e.appendChild(c);e.appendChild(a);document.getElementById("messageBody").innerHTML=d.getMessage("extension_popup_message_body")})});function createOption(d,b){var c=document.createElement("div");c.id=b;c.textContent=d;var a=document.createElement("a");a.textContent=d;a.href="#";c.addEventListener("click",onClick,!0);return c}
function onClick(d){var b;"word"===d.target.id?b="application/vnd.openxmlformats-officedocument.wordprocessingml.document":"point"===d.target.id?b="application/vnd.openxmlformats-officedocument.presentationml.presentation":"sheet"===d.target.id&&(b="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet");chrome.runtime.sendMessage({newCreate:d.target.id,mimeType:b},function(){window.close()})}define("mainPopup",function(){});
